services:
  app:
    build:
      context: ..
      dockerfile: .docker/Dockerfile
    environment:
      HOSTNAME: ${HOSTNAME}
      API_KEY: ${API_KEY}
      LIBRARY_LOGO_URL: ${LIBRARY_LOGO_URL}
      FEATURE_IMAGE_URL: ${FEATURE_IMAGE_URL}
      LIBRARY_NAME_STRING: ${LIBRARY_NAME_STRING}
      ORGANIZATION_NAME_STRING: ${ORGANIZATION_NAME_STRING}
      API_LIBRARY_NAME: ${API_LIBRARY_NAME}
      API_CIRC_DESK: ${API_CIRC_DESK}
      PERMIT_IP_ADDRESSES_JSON: ${PERMIT_IP_ADDRESSES_JSON:-["127.0.0.1","172.16.254.0/24","172.16.15.0/24","172.18.15.0/24"]}